### ISSUE TITLE
Error in distance calc

### ISSUE THREAD

**Issue by JnJSW** [Turfjs/turf-distance#15]
There appears to be an error in how turf calculates distance in certain situations.  Athens, GA, USA and Detroit, MI, USA are ~580 miles apart, however Turf says they are only 70 miles apart.  See the tonicdev below which compares the incorrect output of Turf with the correct output of geolib

https://tonicdev.com/56f0146993422114009787cd/56f0160e1a456f1100df8d9d

**Comment by tmcw** [comment]
GeoJSON coordinate order is longitude, latitude.
