### ISSUE TITLE
vincenty algorithm

### ISSUE THREAD

**Issue by tmcw** [Turfjs/turf-distance#6]
Should you be able to choose algo? Should we switch? And so on: 

* http://en.wikipedia.org/wiki/Vincenty%27s_formulae

**Comment by ezheidtmann** [comment]
The vincenty algorithm may fail for some inputs. See this issue in geopy:

https://github.com/geopy/geopy/issues/30

Or maybe geopy has an error in their implementation.

**Comment by tmcw** [comment]
-> https://github.com/Turfjs?utf8=%E2%9C%93&query=vincent
